/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as addonBilling from "../addonBilling.js";
import type * as admin from "../admin.js";
import type * as alertEmailSettings from "../alertEmailSettings.js";
import type * as analytics from "../analytics.js";
import type * as announcements from "../announcements.js";
import type * as assets from "../assets.js";
import type * as attendance from "../attendance.js";
import type * as awards from "../awards.js";
import type * as callActions from "../callActions.js";
import type * as calls from "../calls.js";
import type * as careerPath from "../careerPath.js";
import type * as cashAdvances from "../cashAdvances.js";
import type * as celebrations from "../celebrations.js";
import type * as chatbot from "../chatbot.js";
import type * as chatbotActions from "../chatbotActions.js";
import type * as courses from "../courses.js";
import type * as crons from "../crons.js";
import type * as dashboardSettings from "../dashboardSettings.js";
import type * as dashboardStats from "../dashboardStats.js";
import type * as dataAccess from "../dataAccess.js";
import type * as dataScopes from "../dataScopes.js";
import type * as directory from "../directory.js";
import type * as directoryFields from "../directoryFields.js";
import type * as documents from "../documents.js";
import type * as employeeDocuments from "../employeeDocuments.js";
import type * as employeeHistory from "../employeeHistory.js";
import type * as engagement from "../engagement.js";
import type * as events from "../events.js";
import type * as expenseCategories from "../expenseCategories.js";
import type * as expensePolicies from "../expensePolicies.js";
import type * as expenses from "../expenses.js";
import type * as featureAddons from "../featureAddons.js";
import type * as featureGate from "../featureGate.js";
import type * as feedback360_cycles from "../feedback360/cycles.js";
import type * as feedback360_reviewers from "../feedback360/reviewers.js";
import type * as feedback360_reviews from "../feedback360/reviews.js";
import type * as feedback360_utils from "../feedback360/utils.js";
import type * as financeApproval from "../financeApproval.js";
import type * as financeApprovalEngine from "../financeApprovalEngine.js";
import type * as financeAuditLog from "../financeAuditLog.js";
import type * as financeDashboard from "../financeDashboard.js";
import type * as footerLinks from "../footerLinks.js";
import type * as forum from "../forum.js";
import type * as fundRequests from "../fundRequests.js";
import type * as gallery from "../gallery.js";
import type * as grading from "../grading.js";
import type * as historyChangeRequests from "../historyChangeRequests.js";
import type * as invoiceEmails from "../invoiceEmails.js";
import type * as invoices from "../invoices.js";
import type * as jobTitles from "../jobTitles.js";
import type * as jobs from "../jobs.js";
import type * as leaveRequests from "../leaveRequests.js";
import type * as letterApprovalTemplates from "../letterApprovalTemplates.js";
import type * as letterContentTemplates from "../letterContentTemplates.js";
import type * as letterEmailSettings from "../letterEmailSettings.js";
import type * as letterMemoSettings from "../letterMemoSettings.js";
import type * as letters from "../letters.js";
import type * as lettersEmail from "../lettersEmail.js";
import type * as lettersEmailInternal from "../lettersEmailInternal.js";
import type * as lib_addons from "../lib/addons.js";
import type * as lib_callQuota from "../lib/callQuota.js";
import type * as lib_countableUsers from "../lib/countableUsers.js";
import type * as lib_email from "../lib/email.js";
import type * as lib_financeConstants from "../lib/financeConstants.js";
import type * as lib_formatJobTitle from "../lib/formatJobTitle.js";
import type * as lib_inviteCode from "../lib/inviteCode.js";
import type * as lib_landingSections from "../lib/landingSections.js";
import type * as lib_menuOverrides from "../lib/menuOverrides.js";
import type * as lib_orgTables from "../lib/orgTables.js";
import type * as lib_planLimits from "../lib/planLimits.js";
import type * as lib_planStorage from "../lib/planStorage.js";
import type * as lib_subscription from "../lib/subscription.js";
import type * as lib_tenant from "../lib/tenant.js";
import type * as lib_trialAccess from "../lib/trialAccess.js";
import type * as lib_userTables from "../lib/userTables.js";
import type * as membership from "../membership.js";
import type * as membershipDashboard from "../membershipDashboard.js";
import type * as messages from "../messages.js";
import type * as notificationPreferences from "../notificationPreferences.js";
import type * as notificationReminders from "../notificationReminders.js";
import type * as notifications from "../notifications.js";
import type * as offboarding from "../offboarding.js";
import type * as okr__helpers from "../okr/_helpers.js";
import type * as okr_keyResults from "../okr/keyResults.js";
import type * as okr_objectives from "../okr/objectives.js";
import type * as okr_stats from "../okr/stats.js";
import type * as omnisearch from "../omnisearch.js";
import type * as onboardUser from "../onboardUser.js";
import type * as onboarding from "../onboarding.js";
import type * as onboarding_checkins from "../onboarding/checkins.js";
import type * as onboarding_resources from "../onboarding/resources.js";
import type * as onboardingCleanup from "../onboardingCleanup.js";
import type * as operationsSettings from "../operationsSettings.js";
import type * as orgAdvanced__scope from "../orgAdvanced/_scope.js";
import type * as orgAdvanced_benchmark from "../orgAdvanced/benchmark.js";
import type * as orgAdvanced_bulkIO from "../orgAdvanced/bulkIO.js";
import type * as orgAdvanced_dottedLines from "../orgAdvanced/dottedLines.js";
import type * as orgAdvanced_headcount from "../orgAdvanced/headcount.js";
import type * as orgAdvanced_history from "../orgAdvanced/history.js";
import type * as orgAdvanced_insights from "../orgAdvanced/insights.js";
import type * as orgAdvanced_jobRoles from "../orgAdvanced/jobRoles.js";
import type * as orgAdvanced_nineBox from "../orgAdvanced/nineBox.js";
import type * as orgAdvanced_scenarios from "../orgAdvanced/scenarios.js";
import type * as orgAdvanced_skills from "../orgAdvanced/skills.js";
import type * as orgAdvanced_spanOfControl from "../orgAdvanced/spanOfControl.js";
import type * as orgAdvanced_succession from "../orgAdvanced/succession.js";
import type * as orgChartPositions from "../orgChartPositions.js";
import type * as orgMenuOverrides from "../orgMenuOverrides.js";
import type * as orgPurge from "../orgPurge.js";
import type * as organization from "../organization.js";
import type * as organizations from "../organizations.js";
import type * as paymentSettings from "../paymentSettings.js";
import type * as payroll__helpers from "../payroll/_helpers.js";
import type * as payroll_components from "../payroll/components.js";
import type * as payroll_dashboard from "../payroll/dashboard.js";
import type * as payroll_periods from "../payroll/periods.js";
import type * as payroll_structures from "../payroll/structures.js";
import type * as performance from "../performance.js";
import type * as planAccess from "../planAccess.js";
import type * as planLimitEmails from "../planLimitEmails.js";
import type * as policies from "../policies.js";
import type * as polls from "../polls.js";
import type * as positionDirectory from "../positionDirectory.js";
import type * as positionLevels from "../positionLevels.js";
import type * as positionMasterData from "../positionMasterData.js";
import type * as positionNomenclature from "../positionNomenclature.js";
import type * as profileChangeRequests from "../profileChangeRequests.js";
import type * as projects from "../projects.js";
import type * as promos from "../promos.js";
import type * as pulse from "../pulse.js";
import type * as recognitions from "../recognitions.js";
import type * as recruitment__helpers from "../recruitment/_helpers.js";
import type * as recruitment_applications from "../recruitment/applications.js";
import type * as recruitment_candidates from "../recruitment/candidates.js";
import type * as recruitment_interviews from "../recruitment/interviews.js";
import type * as recruitment_jobs from "../recruitment/jobs.js";
import type * as reports from "../reports.js";
import type * as roleMenuSettings from "../roleMenuSettings.js";
import type * as roleRequests from "../roleRequests.js";
import type * as roles from "../roles.js";
import type * as rooms from "../rooms.js";
import type * as seatBilling from "../seatBilling.js";
import type * as siteSettings from "../siteSettings.js";
import type * as subscriptionBilling from "../subscriptionBilling.js";
import type * as subscriptionReminders from "../subscriptionReminders.js";
import type * as subscriptionSeed from "../subscriptionSeed.js";
import type * as suggestions from "../suggestions.js";
import type * as superAdmin from "../superAdmin.js";
import type * as superAdminDataAccess from "../superAdminDataAccess.js";
import type * as talent from "../talent.js";
import type * as testData from "../testData.js";
import type * as tickets from "../tickets.js";
import type * as tourProgress from "../tourProgress.js";
import type * as trackCalculations from "../trackCalculations.js";
import type * as training__helpers from "../training/_helpers.js";
import type * as training_ai from "../training/ai.js";
import type * as training_analytics from "../training/analytics.js";
import type * as training_assignments from "../training/assignments.js";
import type * as training_budget from "../training/budget.js";
import type * as training_careers from "../training/careers.js";
import type * as training_engagement from "../training/engagement.js";
import type * as training_external from "../training/external.js";
import type * as training_flashcards from "../training/flashcards.js";
import type * as training_gamification from "../training/gamification.js";
import type * as training_mentors from "../training/mentors.js";
import type * as training_mentorships from "../training/mentorships.js";
import type * as training_microlessons from "../training/microlessons.js";
import type * as training_paths from "../training/paths.js";
import type * as training_peerGroups from "../training/peerGroups.js";
import type * as training_prerequisites from "../training/prerequisites.js";
import type * as training_quizzes from "../training/quizzes.js";
import type * as training_recommendations from "../training/recommendations.js";
import type * as training_roi from "../training/roi.js";
import type * as training_sessions from "../training/sessions.js";
import type * as training_skills from "../training/skills.js";
import type * as training_surveys from "../training/surveys.js";
import type * as travel from "../travel.js";
import type * as trialSettings from "../trialSettings.js";
import type * as userInvites from "../userInvites.js";
import type * as userInvitesInternal from "../userInvitesInternal.js";
import type * as userPurge from "../userPurge.js";
import type * as userSettings from "../userSettings.js";
import type * as users from "../users.js";
import type * as welcomePage from "../welcomePage.js";
import type * as wiki from "../wiki.js";
import type * as zoomMeetings from "../zoomMeetings.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  addonBilling: typeof addonBilling;
  admin: typeof admin;
  alertEmailSettings: typeof alertEmailSettings;
  analytics: typeof analytics;
  announcements: typeof announcements;
  assets: typeof assets;
  attendance: typeof attendance;
  awards: typeof awards;
  callActions: typeof callActions;
  calls: typeof calls;
  careerPath: typeof careerPath;
  cashAdvances: typeof cashAdvances;
  celebrations: typeof celebrations;
  chatbot: typeof chatbot;
  chatbotActions: typeof chatbotActions;
  courses: typeof courses;
  crons: typeof crons;
  dashboardSettings: typeof dashboardSettings;
  dashboardStats: typeof dashboardStats;
  dataAccess: typeof dataAccess;
  dataScopes: typeof dataScopes;
  directory: typeof directory;
  directoryFields: typeof directoryFields;
  documents: typeof documents;
  employeeDocuments: typeof employeeDocuments;
  employeeHistory: typeof employeeHistory;
  engagement: typeof engagement;
  events: typeof events;
  expenseCategories: typeof expenseCategories;
  expensePolicies: typeof expensePolicies;
  expenses: typeof expenses;
  featureAddons: typeof featureAddons;
  featureGate: typeof featureGate;
  "feedback360/cycles": typeof feedback360_cycles;
  "feedback360/reviewers": typeof feedback360_reviewers;
  "feedback360/reviews": typeof feedback360_reviews;
  "feedback360/utils": typeof feedback360_utils;
  financeApproval: typeof financeApproval;
  financeApprovalEngine: typeof financeApprovalEngine;
  financeAuditLog: typeof financeAuditLog;
  financeDashboard: typeof financeDashboard;
  footerLinks: typeof footerLinks;
  forum: typeof forum;
  fundRequests: typeof fundRequests;
  gallery: typeof gallery;
  grading: typeof grading;
  historyChangeRequests: typeof historyChangeRequests;
  invoiceEmails: typeof invoiceEmails;
  invoices: typeof invoices;
  jobTitles: typeof jobTitles;
  jobs: typeof jobs;
  leaveRequests: typeof leaveRequests;
  letterApprovalTemplates: typeof letterApprovalTemplates;
  letterContentTemplates: typeof letterContentTemplates;
  letterEmailSettings: typeof letterEmailSettings;
  letterMemoSettings: typeof letterMemoSettings;
  letters: typeof letters;
  lettersEmail: typeof lettersEmail;
  lettersEmailInternal: typeof lettersEmailInternal;
  "lib/addons": typeof lib_addons;
  "lib/callQuota": typeof lib_callQuota;
  "lib/countableUsers": typeof lib_countableUsers;
  "lib/email": typeof lib_email;
  "lib/financeConstants": typeof lib_financeConstants;
  "lib/formatJobTitle": typeof lib_formatJobTitle;
  "lib/inviteCode": typeof lib_inviteCode;
  "lib/landingSections": typeof lib_landingSections;
  "lib/menuOverrides": typeof lib_menuOverrides;
  "lib/orgTables": typeof lib_orgTables;
  "lib/planLimits": typeof lib_planLimits;
  "lib/planStorage": typeof lib_planStorage;
  "lib/subscription": typeof lib_subscription;
  "lib/tenant": typeof lib_tenant;
  "lib/trialAccess": typeof lib_trialAccess;
  "lib/userTables": typeof lib_userTables;
  membership: typeof membership;
  membershipDashboard: typeof membershipDashboard;
  messages: typeof messages;
  notificationPreferences: typeof notificationPreferences;
  notificationReminders: typeof notificationReminders;
  notifications: typeof notifications;
  offboarding: typeof offboarding;
  "okr/_helpers": typeof okr__helpers;
  "okr/keyResults": typeof okr_keyResults;
  "okr/objectives": typeof okr_objectives;
  "okr/stats": typeof okr_stats;
  omnisearch: typeof omnisearch;
  onboardUser: typeof onboardUser;
  onboarding: typeof onboarding;
  "onboarding/checkins": typeof onboarding_checkins;
  "onboarding/resources": typeof onboarding_resources;
  onboardingCleanup: typeof onboardingCleanup;
  operationsSettings: typeof operationsSettings;
  "orgAdvanced/_scope": typeof orgAdvanced__scope;
  "orgAdvanced/benchmark": typeof orgAdvanced_benchmark;
  "orgAdvanced/bulkIO": typeof orgAdvanced_bulkIO;
  "orgAdvanced/dottedLines": typeof orgAdvanced_dottedLines;
  "orgAdvanced/headcount": typeof orgAdvanced_headcount;
  "orgAdvanced/history": typeof orgAdvanced_history;
  "orgAdvanced/insights": typeof orgAdvanced_insights;
  "orgAdvanced/jobRoles": typeof orgAdvanced_jobRoles;
  "orgAdvanced/nineBox": typeof orgAdvanced_nineBox;
  "orgAdvanced/scenarios": typeof orgAdvanced_scenarios;
  "orgAdvanced/skills": typeof orgAdvanced_skills;
  "orgAdvanced/spanOfControl": typeof orgAdvanced_spanOfControl;
  "orgAdvanced/succession": typeof orgAdvanced_succession;
  orgChartPositions: typeof orgChartPositions;
  orgMenuOverrides: typeof orgMenuOverrides;
  orgPurge: typeof orgPurge;
  organization: typeof organization;
  organizations: typeof organizations;
  paymentSettings: typeof paymentSettings;
  "payroll/_helpers": typeof payroll__helpers;
  "payroll/components": typeof payroll_components;
  "payroll/dashboard": typeof payroll_dashboard;
  "payroll/periods": typeof payroll_periods;
  "payroll/structures": typeof payroll_structures;
  performance: typeof performance;
  planAccess: typeof planAccess;
  planLimitEmails: typeof planLimitEmails;
  policies: typeof policies;
  polls: typeof polls;
  positionDirectory: typeof positionDirectory;
  positionLevels: typeof positionLevels;
  positionMasterData: typeof positionMasterData;
  positionNomenclature: typeof positionNomenclature;
  profileChangeRequests: typeof profileChangeRequests;
  projects: typeof projects;
  promos: typeof promos;
  pulse: typeof pulse;
  recognitions: typeof recognitions;
  "recruitment/_helpers": typeof recruitment__helpers;
  "recruitment/applications": typeof recruitment_applications;
  "recruitment/candidates": typeof recruitment_candidates;
  "recruitment/interviews": typeof recruitment_interviews;
  "recruitment/jobs": typeof recruitment_jobs;
  reports: typeof reports;
  roleMenuSettings: typeof roleMenuSettings;
  roleRequests: typeof roleRequests;
  roles: typeof roles;
  rooms: typeof rooms;
  seatBilling: typeof seatBilling;
  siteSettings: typeof siteSettings;
  subscriptionBilling: typeof subscriptionBilling;
  subscriptionReminders: typeof subscriptionReminders;
  subscriptionSeed: typeof subscriptionSeed;
  suggestions: typeof suggestions;
  superAdmin: typeof superAdmin;
  superAdminDataAccess: typeof superAdminDataAccess;
  talent: typeof talent;
  testData: typeof testData;
  tickets: typeof tickets;
  tourProgress: typeof tourProgress;
  trackCalculations: typeof trackCalculations;
  "training/_helpers": typeof training__helpers;
  "training/ai": typeof training_ai;
  "training/analytics": typeof training_analytics;
  "training/assignments": typeof training_assignments;
  "training/budget": typeof training_budget;
  "training/careers": typeof training_careers;
  "training/engagement": typeof training_engagement;
  "training/external": typeof training_external;
  "training/flashcards": typeof training_flashcards;
  "training/gamification": typeof training_gamification;
  "training/mentors": typeof training_mentors;
  "training/mentorships": typeof training_mentorships;
  "training/microlessons": typeof training_microlessons;
  "training/paths": typeof training_paths;
  "training/peerGroups": typeof training_peerGroups;
  "training/prerequisites": typeof training_prerequisites;
  "training/quizzes": typeof training_quizzes;
  "training/recommendations": typeof training_recommendations;
  "training/roi": typeof training_roi;
  "training/sessions": typeof training_sessions;
  "training/skills": typeof training_skills;
  "training/surveys": typeof training_surveys;
  travel: typeof travel;
  trialSettings: typeof trialSettings;
  userInvites: typeof userInvites;
  userInvitesInternal: typeof userInvitesInternal;
  userPurge: typeof userPurge;
  userSettings: typeof userSettings;
  users: typeof users;
  welcomePage: typeof welcomePage;
  wiki: typeof wiki;
  zoomMeetings: typeof zoomMeetings;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
